Add support for Astro
XAMPPRocky/tokei pull request #966
Opened 2023-01-05 11:16 UTC by zihan-ch

2023-01-16 15:19 UTC, glennj requested changes

2023-01-16 15:19 UTC, glennj commented on languages.json
> +      "multi_line_comments": [["/*", "*/"], ["<!--", "-->"],
You've got a missing close bracket 
```suggestion
      "multi_line_comments": [["/*", "*/"], ["<!--", "-->"]],
```

2023-04-27 07:24 UTC, npup commented
I'd love this one to get merged! Is there anything I can do to help to make it happen?

2023-04-27 07:55 UTC, XAMPPRocky commented
Thank you for your PR, and congrats on your first contribution! 🎉

2023-04-27 07:55 UTC, merged